"""empty message

Revision ID: 26f68afd5da3
Revises: None
Create Date: 2015-03-26 20:19:17.626536

"""

# revision identifiers, used by Alembic.
revision = '26f68afd5da3'
down_revision = None

from alembic import op
import sqlalchemy as sa
import db


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('repository_data', db.types.json.JSONEncodedDict(), nullable=True),
    sa.Column('project_data', db.types.json.JSONEncodedDict(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sha', sa.String(length=128), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('data', db.types.json.JSONEncodedDict(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('started_date', sa.DateTime(), nullable=True),
    sa.Column('finished_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logchunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logchunk')
    op.drop_table('task')
    op.drop_table('project')
    op.drop_table('user')
    ### end Alembic commands ###
