"""empty message

Revision ID: 4666d6b4335b
Revises: None
Create Date: 2015-03-18 13:10:28.777434

"""

# revision identifiers, used by Alembic.
revision = '4666d6b4335b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
