"""empty message

Revision ID: 4baa48381c55
Revises: 4666d6b4335b
Create Date: 2015-03-18 13:17:33.486971

"""

# revision identifiers, used by Alembic.
revision = '4baa48381c55'
down_revision = '4666d6b4335b'

from alembic import op
import sqlalchemy as sa
import db

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('vcs', sa.String(length=64), nullable=False),
    sa.Column('data', db.types.json.JSONEncodedDict(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('data', db.types.json.JSONEncodedDict(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_app_repository_id', 'app', ['repository_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ref', sa.String(length=128), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('data', db.types.json.JSONEncodedDict(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'environment', 'number', name='unq_task_number')
    )
    op.create_index('idx_task_app_id', 'task', ['app_id'], unique=False)
    op.create_index('idx_task_user_id', 'task', ['user_id'], unique=False)
    op.create_table('logchunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'offset', name='unq_logchunk_source_offset')
    )
    op.create_index('idx_logchunk_task_id', 'logchunk', ['task_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logchunk_task_id', table_name='logchunk')
    op.drop_table('logchunk')
    op.drop_index('idx_task_user_id', table_name='task')
    op.drop_index('idx_task_app_id', table_name='task')
    op.drop_table('task')
    op.drop_index('idx_app_repository_id', table_name='app')
    op.drop_table('app')
    op.drop_table('user')
    op.drop_table('repository')
    ### end Alembic commands ###
